const WORDS=[
{word:"GOAL",hint:"A target in a game"},{word:"GOALIE",hint:"The player who guards the goal"},{word:"LEADER",hint:"A person who guides a group"},{word:"STANDS",hint:"Seats for a crowd at a game"},{word:"ABOARD",hint:"On or inside a ship, train, or plane"},{word:"CONDUCTOR",hint:"A person who leads an orchestra or checks train tickets"},{word:"FANCY",hint:"Decorative or special"},{word:"SPACE",hint:"The area beyond Earth"},{word:"FLUFFY",hint:"Soft and full of fluff"},{word:"COZY",hint:"Warm, comfortable, and snug"},{word:"SUNNY",hint:"Bright with sunshine"},{word:"SNOWY",hint:"Covered with or full of snow"},{word:"AGREE",hint:"To have the same opinion"},{word:"CLUBHOUSE",hint:"A building used by a club or team"},{word:"DECORATE",hint:"To make something look pretty"},{word:"MEASURE",hint:"To find the size or amount of something"},{word:"HAIL",hint:"Small balls of ice that fall from clouds"},{word:"LIGHTNING",hint:"A bright flash in a storm"},{word:"THUNDER",hint:"The loud sound during a storm"},{word:"TORNADO",hint:"A powerful spinning column of air"}];
const MAP=["###########","#...#.....#","#.#.#.###.#","#.#...#...#","#.###.#.#.#","#.....#.#.#","###.###.#.#","#...#...#.#","#.#.#.###.#","#.........#","###########"];
const $=id=>document.getElementById(id);let player={x:1,y:1},dots=[],deck=[],qIndex=0,score=0,locked=false,soundOn=true,audioCtx,questionActive=false,won=false;
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function tone(ok=true){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=ok?650:190;g.gain.value=.055;o.start();o.stop(audioCtx.currentTime+(ok?.12:.18));}catch(e){}}
function setup(){player={x:1,y:1};deck=shuffle(WORDS).slice(0,10);qIndex=0;score=0;questionActive=false;won=false;$('result').hidden=true;$('questionModal').hidden=true;const candidates=[];MAP.forEach((row,y)=>[...row].forEach((v,x)=>{if(v!== '#'&&!(x===1&&y===1)&&!(x===9&&y===9))candidates.push({x,y})}));dots=shuffle(candidates).slice(0,10);render();updateStats();$('progress').textContent='DOTS 0 / 10';}
function render(){const board=$('board');board.innerHTML='';MAP.forEach((row,y)=>[...row].forEach((v,x)=>{const c=document.createElement('div');c.className='cell'+(v==='#'?' wall':'');if(dots.some(d=>d.x===x&&d.y===y))c.classList.add('dot');if(x===9&&y===9)c.classList.add('exit');if(player.x===x&&player.y===y){c.classList.add('player');c.style.setProperty('--turn',player.turn||'0deg')}board.appendChild(c)}));}
function updateStats(){$('score').textContent=score;$('scoreTop').textContent=String(score).padStart(3,'0');$('answered').textContent=qIndex;$('dotsLeft').textContent=dots.length;$('progress').textContent='DOTS '+qIndex+' / 10'}
function move(dx,dy){if(questionActive||won)return;const nx=player.x+dx,ny=player.y+dy;if(!MAP[ny]||MAP[ny][nx]==='#')return;player={x:nx,y:ny,turn:dx===1?'0deg':dx===-1?'180deg':dy===1?'90deg':'-90deg'};const idx=dots.findIndex(d=>d.x===nx&&d.y===ny);if(idx>=0){dots.splice(idx,1);render();openQuestion();return}if(nx===9&&ny===9&&qIndex>=10){finish()}else{render()}tone(true)}
function openQuestion(){if(qIndex>=10){finish();return}questionActive=true;locked=false;const item=deck[qIndex];item.missingIndex=Math.floor(Math.random()*item.word.length);item.answer=item.word[item.missingIndex];$('qCount').textContent='QUESTION '+(qIndex+1)+' / 10';$('word').innerHTML=[...item.word].map((c,i)=>'<span class="letter '+(i===item.missingIndex?'missing':'')+'">'+(i===item.missingIndex?'_':c)+'</span>').join('');$('hint').textContent=item.hint;$('feedback').textContent='Choose the missing letter!';$('feedback').className='feedback';const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.replace(item.answer,'');const opts=shuffle([item.answer,...shuffle([...alphabet]).slice(0,3)]);$('choices').innerHTML=opts.map(c=>'<button class="choice" type="button" data-letter="'+c+'">'+c+'</button>').join('');$('choices').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.letter,b)));$('questionModal').hidden=false}
function answer(letter,button){if(locked)return;locked=true;const item=deck[qIndex],ok=letter===item.answer;$('choices').querySelectorAll('button').forEach(b=>{b.disabled=true;if(b.dataset.letter===item.answer)b.classList.add('correct')});if(!ok)button.classList.add('wrong');if(ok){score+=10;$('feedback').textContent='✨ Correct! Keep moving!';$('feedback').className='feedback good'}else{$('feedback').textContent='The correct letter is '+item.answer+'. Keep going!';$('feedback').className='feedback bad'}tone(ok);qIndex++;updateStats();setTimeout(()=>{ $('questionModal').hidden=true;questionActive=false;if(qIndex>=10){finish()}else{render()}},ok?850:1300)}
function finish(){won=true;questionActive=false;$('questionModal').hidden=true;$('result').hidden=false;$('resultText').textContent='You completed '+qIndex+' out of 10 word challenges and scored '+score+' out of 100 points!';}
$('again').addEventListener('click',setup);$('soundBtn').addEventListener('click',()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊 Sound':'🔇 Sound'});document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('click',()=>{const d=b.dataset.dir;move(d==='left'?-1:d==='right'?1:0,d==='up'?-1:d==='down'?1:0)}));document.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),dirs={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(dirs[k]){e.preventDefault();move(...dirs[k])}});let touchStart=null;$('maze').addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY}},{passive:true});$('maze').addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;if(Math.abs(dx)>Math.abs(dy))move(dx>0?1:-1,0);else move(0,dy>0?1:-1)},{passive:true});setup();