const WORDS=[
{word:"GOAL",hint:"A target in a game"},{word:"GOALIE",hint:"The player who guards the goal"},{word:"LEADER",hint:"A person who guides a group"},{word:"STANDS",hint:"Seats for a crowd at a game"},{word:"ABOARD",hint:"On or inside a ship, train, or plane"},{word:"CONDUCTOR",hint:"A person who leads an orchestra or checks train tickets"},{word:"FANCY",hint:"Decorative or special"},{word:"SPACE",hint:"The area beyond Earth"},{word:"FLUFFY",hint:"Soft and full of fluff"},{word:"COZY",hint:"Warm, comfortable, and snug"},{word:"SUNNY",hint:"Bright with sunshine"},{word:"SNOWY",hint:"Covered with or full of snow"},{word:"AGREE",hint:"To have the same opinion"},{word:"CLUBHOUSE",hint:"A building used by a club or team"},{word:"DECORATE",hint:"To make something look pretty"},{word:"MEASURE",hint:"To find the size or amount of something"},{word:"HAIL",hint:"Small balls of ice that fall from clouds"},{word:"LIGHTNING",hint:"A bright flash in a storm"},{word:"THUNDER",hint:"The loud sound during a storm"},{word:"TORNADO",hint:"A powerful spinning column of air"}];
const $=id=>document.getElementById(id);let deck=[],index=0,score=0,streak=0,answered=0,locked=false,soundOn=true,audioCtx;
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function speakTone(ok){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=ok?660:180;o.type='sine';g.gain.value=.07;o.start();o.stop(audioCtx.currentTime+(ok?.12:.2));}catch(e){}}
function start(){deck=shuffle(WORDS);index=score=streak=answered=0;locked=false;$('result').hidden=true;$('score').textContent='0';$('scoreTop').textContent='000';$('streak').textContent='0';$('answered').textContent='0';$('choices').hidden=false;$('progress').textContent='WORD 1 / 20';render()}
function render(){locked=false;const item=deck[index];const missingIndex=Math.floor(Math.random()*item.word.length);item.missingIndex=missingIndex;item.answer=item.word[missingIndex];$('word').innerHTML=[...item.word].map((c,i)=>'<span class="letter '+(i===missingIndex?'missing':'')+'">'+(i===missingIndex?'_':c)+'</span>').join('');$('hint').textContent=item.hint;$('feedback').textContent='Choose the missing letter!';$('feedback').className='feedback';$('progress').textContent='WORD '+(index+1)+' / '+deck.length;
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.replace(item.answer,'');const opts=shuffle([item.answer,...shuffle([...alphabet]).slice(0,3)]);$('choices').innerHTML=opts.map(c=>'<button class="choice" type="button" data-letter="'+c+'" aria-label="Choose letter '+c+'">'+c+'</button>').join('');$('choices').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.letter,b)))}
function choose(letter,button){if(locked)return;locked=true;const item=deck[index],ok=letter===item.answer;const buttons=[...$('choices').querySelectorAll('button')];buttons.forEach(b=>{b.disabled=true;if(b.dataset.letter===item.answer)b.classList.add('correct')});if(!ok)button.classList.add('wrong');if(ok){score+=10;streak++;$('feedback').textContent='✨ Correct! Great job!';$('feedback').className='feedback good';}else{streak=0;$('feedback').textContent='Almost! The correct letter is '+item.answer+'.';$('feedback').className='feedback bad';}speakTone(ok);answered++;$('score').textContent=score;$('scoreTop').textContent=String(score).padStart(3,'0');$('streak').textContent=streak;$('answered').textContent=answered;setTimeout(()=>{index++;if(index>=deck.length)finish();else render()},ok?850:1250)}
function finish(){$('choices').hidden=true;$('result').hidden=false;$('resultText').textContent='You scored '+score+' out of '+(WORDS.length*10)+' points and completed all '+WORDS.length+' words!';$('progress').textContent='GAME COMPLETE';$('word').textContent='★ WELL DONE ★';$('hint').textContent='You are a Word Arcade champion!';$('feedback').textContent='';}
$('again').addEventListener('click',start);$('soundBtn').addEventListener('click',()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊 Sound':'🔇 Sound';});start();